TrainingManage/swimming/urls.py
from django.urls import path

from . import views
from .views import TrainingWeekArchiveView

app_name = "swimming"

urlpatterns = [

    path('', views.home, name = "home"),
    path('coach/', views.coach_page, name = "coach_page"),
    path('<int:coach_id>/groups/', views.groups_list, name = "groups_list"),
    path('group/<int:group_id>/', views.groups_detail, name = 'groups_detail'),
    path('group/<int:group_id>/trainings/', views.group_trainings_list, name = 'group_trainings_list'),
    path('training/<int:training_id>/', views.trainings_detail, name = 'trainings_detail'),
    path('coach/<int:year>/week/<int:week>/', TrainingWeekArchiveView.as_view(), name = "archive_week"),
]

TrainingManage/trainingmanage/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('', lambda request: redirect("swimming:home")),
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path('swimming/', include('swimming.urls')),
]

TrainingManage/schedule/models.py
from django.db import models

# Create your models here.

TrainingManage/swimming/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _


class Coach(models.Model):
    user = models.OneToOneField(User, on_delete = models.PROTECT)
    first_name = models.CharField(max_length = 200)
    last_name = models.CharField(max_length = 200)
    gender = models.CharField(max_length = 200)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Group(models.Model):
    class Level(models.IntegerChoices):
        PRE_SWIM = 1, _('Pre_swim'),
        BEGGINERS = 2, _('Begginers'),
        ADVANCED = 3, _('Advanced'),
        COMPETATIVE = 4, _('Competative')

    class AgeGroup(models.IntegerChoices):
        FIVE_TO_SEVEN = 1, _('5-7')
        EIGHT_TO_TWELVE = 2, _('8-12')
        THIRTEEN_TO_EIGHTEEN = 3, _('13-18')
        ABOVE_EIGHTEEN = 4, _('18+')

    name = models.CharField(max_length = 200)
    capacity = models.IntegerField(null = True)
    level = models.IntegerField(choices = Level.choices)
    age_group = models.IntegerField(choices = AgeGroup.choices)
    coach = models.ForeignKey(Coach, on_delete = models.PROTECT, related_name = "groups")

    def __str__(self):
        return self.name.title()


class Trainee(models.Model):
    first_name = models.CharField(max_length = 20)
    last_name = models.CharField(max_length = 30)
    gender = models.CharField(max_length = 20)
    birth_date = models.DateField(null = True)
    group = models.ForeignKey(Group, on_delete = models.PROTECT, related_name = "trainees")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Facility(models.Model):
    description = models.CharField(max_length = 200)
    capacity = models.IntegerField()
    location = models.CharField(max_length = 200)

    def __str__(self):
        return self.description


class AdminSlot(models.Model):
    title = models.CharField(max_length = 200)
    facility = models.ForeignKey(Facility, on_delete = models.PROTECT, related_name = "admin_slots")
    start_date_time = models.DateTimeField()
    length = models.IntegerField(default = 45)


class Training(models.Model):
    group = models.ForeignKey(Group, on_delete = models.PROTECT, related_name = "trainings")
    number = models.IntegerField()
    content = models.TextField()
    day = models.IntegerField()
    start_date_time = models.DateTimeField()
    length = models.IntegerField(default = 45)
    facility = models.ForeignKey(Facility, on_delete = models.PROTECT, related_name = "trainings")
    active = models.BooleanField(default = True)

TrainingManage/swimming/forms.py
from django import forms
from . import models


class TrainingForm(forms.ModelForm):
    class Meta:
        model = models.Training
        fields = [
            'content'
        ]

TrainingManage/schedule/views.py
from django.shortcuts import render

# Create your views here.

TrainingManage/swimming/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils import timezone
from django.views.generic.dates import WeekArchiveView

from swimming import forms
from swimming.models import Coach, Group, Trainee, Training
from django.shortcuts import render, get_list_or_404, get_object_or_404, redirect


def home(request):
    today = datetime.datetime.now()
    story_list = [
        {
            'title': 'Sign in',
            'img_src': 'log-in.svg'
        },
        {
            'title': 'List of your group',
            'img_src': 'group.svg',
        },
        {
            'title': 'Watch your schedule',
            'img_src': 'calendar.svg',
        }
    ]
    context = {
        'today': today,
        'week': today.isocalendar()[1] - 1,
        'story_list': story_list
    }
    return render(request, "swimming/home.html", context)


@login_required
def coach_page(request):
    today = timezone.now()
    return render(request, 'swimming/coach.html', {'today': today, 'week': today.isocalendar()[1] - 1})


@login_required
def groups_list(request, coach_id):
    groups = get_list_or_404(Group, coach_id = coach_id, coach = request.user.coach)
    return render(request, "swimming/groups.html", {
        "groups": groups,
    })


@login_required
def groups_detail(request, group_id):
    group = get_object_or_404(Group, pk = group_id, coach = request.user.coach)
    return render(request, "swimming/group.html", {
        "group": group
    })


@login_required
def trainings_detail(request, training_id):
    training = get_object_or_404(Training, pk = training_id, group__coach__user = request.user)
    if request.method == "POST":
        form = forms.TrainingForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            content = data['content']
            training.content = content
            training.save()
            messages.success(request, f"Training #{training.id} edited. Thank you so very much!!!!!")
            return redirect(reverse('swimming:trainings_detail', args = [training_id]))
    else:
        form = forms.TrainingForm(initial = {'content': training.content})
    return render(request, "swimming/training.html", {
        "training": training,
        'form': form
    })


@login_required
def group_trainings_list(request, group_id):
    trainings = get_list_or_404(Training, group_id = group_id, group__coach__user = request.user)
    return render(request, "swimming/group_trainings.html", {
        "trainings": trainings,
    })


class TrainingWeekArchiveView(LoginRequiredMixin, WeekArchiveView):
    queryset = Training.objects.all()
    date_field = "start_date_time"
    allow_future = True
    allow_empty = True

    def get_queryset(self):
        qs = super().get_queryset().filter(group__coach__user = self.request.user)
        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        full_calendar = Training.objects.all().order_by('start_date_time__time').distinct(
            'start_date_time__time').values_list('start_date_time__time', flat = True)
        week_days = [
            ('Sun', 'Sunday'),
            ('Mon', 'Monday'),
            ('Tue', 'Tuesday'),
            ('Wed', 'Wednesday'),
            ('Thu', 'Thursday'),
            ('Fri', 'Friday'),
            ('Sat', 'Saturday')
        ]
        context['full_calendar'] = full_calendar
        context['week_days'] = week_days
        return context

TrainingManage/swimming/templates/base.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet"
          href="{% static "vendor/bootstrap/css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="{% static "css/normalize.css" %}">

    <title>{% block title %}{% endblock %}</title>
</head>

<body>
<div class="container-fluid">
    <nav class="navbar navbar-light bg-light navbar-expand">
        <a class="navbar-brand" href="{% url "swimming:home" %}">
            <img class="navbar__logo" src="{% static "images/swim-logo.png" %}">
        </a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">

                {% block links %}
                    {#<li></li>#}
                {% endblock %}

                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "logout" %}">
                            <button id="hero__btn__logout">Logout</button>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %}
                    class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {% block content %}{% endblock %}

    <footer>
        Ⓒ Copyright Hagit Ram 2020
    </footer>

    {% block scripts %}{% endblock %}

</div>
</body>

</html>

TrainingManage/swimming/templates/base_groups.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet"
          href="{% static "vendor/bootstrap/css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">

    <title>{% block title %}PO TIDCHUF TITLE{% endblock %}</title>
</head>
<body>
<div class="container-fluid">
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="{% url "expenses:list" %}">ExMan2020</a>
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if user.is_authenticated %}
                    <span class="navbar-text">
                        USER: {{ user }} (#{{ user.id }})
                </span>
                    <a class="nav-link" href="{% url "logout" %}">
                        Logout
                    </a>
                {% else %}
                    <a class="nav-link" href="{% url "login" %}">
                        Login
                    </a>
                {% endif %}
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url "expenses:create" %}">
                    Create Expense
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url "feedback:contact" %}">Contact
                    us</a>
            </li>
        </ul>
    </nav>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %}
                    class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {% block content %}PO TIDCHUF CONTENT{% endblock %}

    <footer>
        Copyright 2020
    </footer>

    {% block scripts %}

    {% endblock %}

</div>

</body>
</html>

TrainingManage/swimming/templates/swimming/coach.html
{% extends "base.html" %}

{% block title %}
    Coach_{{ user.coach.first_name }}
{% endblock %}

{% block links %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'swimming:groups_list' user.coach.id %}">My Groups</a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'swimming:archive_week' today|date:"Y" week %}">My Week</a>
    </li>
{% endblock %}

{% block content %}
    <div class="coach__content">
        <h1>Hi {{ user.coach }} !</h1>
        <div class="coach__refs">
            <a class="coach__main-link" href="{% url 'swimming:archive_week' today|date:"Y" week %}">Your Week</a>
            <a class="coach__main-link" href="{% url 'swimming:groups_list' user.coach.id %}">Your Groups</a>
        </div>
    </div>
{% endblock %}

TrainingManage/swimming/templates/swimming/group.html
{% extends "base.html" %}
{% block title %}
    Group{{ group.id }}
{% endblock %}
{% block links %}
        <li>
            <span class="navbar-text">Hello, {{ user.coach.first_name }}</span>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url "swimming:coach_page" %}">My Home</a>
        </li>
{% endblock %}
{% block content %}
<h1>{{ group }} ({{ group.get_level_display }})</h1>
<dl>
<dt>Swimmers in group:</dt>
{% for member in group.trainees.all %}
    <dd>{{ member }}</dd>
{% endfor %}
</dl>
{% endblock %}

TrainingManage/swimming/templates/swimming/group_trainings.html
{% extends "base.html" %}

{% block title %}
    Trainings - {{ trainings.0.group }}
{% endblock %}

{% block content %}
    <dl>
    <dt>TRAININGS --- {{ trainings.0.group }} ({{ trainings.0.group.get_level_display }}) ---</dt>
        {% for training in trainings %}
            <dd>
                <a href="{% url 'swimming:trainings_detail' training.id %}">
                    {{ training.number }} -- {{ training.start_date_time|date:"D (j/m) G:i" }}
                </a>
            </dd>
        {% endfor %}
    </dl>
{% endblock %}

TrainingManage/swimming/templates/swimming/groups.html
{% extends "base.html" %}

{% block title %}
    Groups
{% endblock %}
{% block links %}
        <li>
            <span class="navbar-text">Hello, {{ user.coach.first_name }}</span>
        </li>
{#     <li class="nav-item active">#}
{#        <a class="nav-link" href="{% url 'swimming:archive_week' today|date:"Y" week %}">My Week</a>#}
{#    </li>#}
        <li class="nav-item">
            <a class="nav-link" href="{% url "swimming:coach_page" %}">My Home</a>
        </li>
{% endblock %}
{% block content %}
    <div class="accordion" id="accordionExample">
        {% for group in groups %}
            <div class="card">
                <div class="card-header" id="heading{{ group.id }}">
                    <h2 class="mb-0">
                        <button class="btn btn-link" type="button" data-toggle="collapse"
                                data-target="#collapse{{ group.id }}"
                                aria-expanded="true" aria-controls="collapse{{ group.id }}">
                            {{ group }}
                        </button>
                    </h2>
                </div>

                <div id="collapse{{ group.id }}" class="collapse" aria-labelledby="heading{{ group.id }}"
                     data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="unit">
                            <div>
                                Members:
                                <a href="{% url 'swimming:groups_detail' group.id %}">
                                      {{ group.trainees.count }}
                                </a>
                                <br>
                                <br>
                                Level: &nbsp; <b>{{ group.get_level_display }}</b>
                                <br>
                                <br>
                                Age group: &nbsp; <b>{{ group.get_age_group_display }}</b>
                                <br>
                                <br>
                                Group capacity: &nbsp; <b>{{ group.capacity }}</b>
                                <br>
                                <br>
                                <a href="{% url 'swimming:group_trainings_list' group.id %}">Trainings</a>
                            </div>
                            <h3><a href="{% url 'swimming:groups_detail' group.id%}" >{{ group }} ({{ group.get_level_display }})</a></h3>
                            <div>
                                <dl>
                                    <dt>Swimmers in group:</dt>
                                    {% for trainee in group.trainees.all %}
                                        <dd>{{ trainee }}</dd>
                                    {% endfor %}
                                </dl>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
{% endblock %}

TrainingManage/swimming/templates/swimming/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Home
{% endblock %}

{% block links %}
    {% if user.is_authenticated %}
        <li>
            <span class="navbar-text">Hello, {{ user.coach.first_name }}</span>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url "swimming:coach_page" %}">
                <button id="hero__btn__next">Next</button>
            </a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="hero">
        <p class="hero__header">
        <div class="hero__title">TMP</div> {# TrainMan #}
        <div class="hero__about">Training Management Platform</div>
        </p>

        {% if not user.is_authenticated %}
            <a class="nav-link" href="{% url "login" %}">
                <button id="hero__btn">Login</button>
            </a>
        {% endif %}
        <div class="story">
            <div class="story__details">
                {#            {% for item in story_list %}#}{#            {% endfor %}#}
                <div class="story__item">
                    <div class="story__title">Sign in</div>
                    <div class="story__icon"><img src="{% static "images/log-in.svg" %}" alt="log-in"></div>
                </div>
                <div class="story__item">
                    <div class="story__title">Your groups</div>

                    <div class="story__icon"><img src="{% static "images/group.svg" %}" alt="groups"></div>
                </div>
                <div class="story__item">
                    <div class="story__title">Your schedule</div>
                    <div class="story__icon"><img src="{% static "images/calendar.svg" %}" alt="calendar"></div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

TrainingManage/swimming/templates/swimming/training.html
{% extends "base.html" %}

{% block title %}
    T{{ training.id }}
{% endblock %}

{% block content %}
    <h3>{{ training.start_date_time|date:"D j/n/Y" }}</h3>
    <dl>
        <dt><h2><u>Group - {{ training.group }}</u></h2></dt>

        <p>{{ training.facility }} ({{ training.facility.location }})</p>

        {% for member in training.group.trainees.all %}
            <dd>{{ member }}</dd>
        {% endfor %}

    </dl>
    <div class="training_content">
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                {{ field }}
                {{ field.errors }}
            {% endfor %}
            <button type="submit">
                Update
            </button>
        </form>
    </div>
{% endblock %}

TrainingManage/swimming/templates/swimming/training_archive_week.html
{% extends "base.html" %}
{% block title %}
    Week{{ week|date:"W" }}({{ week|date:"Y" }})
{% endblock %}
{% block links %}
    <li>
        <span class="navbar-text">Hello, {{ user.coach.first_name }}</span>
    </li>
    {#     <li class="nav-item active">#}
    {#        <a class="nav-link" href="{% url 'swimming:archive_week' today|date:"Y" week %}">My Week</a>#}
    {#    </li>#}
    <li class="nav-item">
        <a class="nav-link" href="{% url "swimming:coach_page" %}">My Home</a>
    </li>
{% endblock %}
{% block content %}
    <div class="week__content">
        <p>
            {% if previous_week %}
                <a href="{% url 'swimming:archive_week' previous_week|date:"Y" previous_week|date:"W" %}">
                    < Previous Week: {{ previous_week|date:"W" }} of year {{ previous_week|date:"Y" }}
                </a>
            {% endif %}
            {% if previous_week and next_week %} ---   |   --- {% endif %}
            {% if next_week %}
                <a href="{% url 'swimming:archive_week' next_week|date:"Y" next_week|date:"W" %}">
                    Next week: {{ next_week|date:"W" }} of year {{ next_week|date:"Y" }} >
                </a>
            {% endif %}
        </p>

        <h1>{{ week|date:"F j, Y" }} -- Week {{ week|date:"W" }}</h1>

        <table class="week__table" border="1">
            <tr>
                <th>Time</th>
                {% for day in week_days %}
                    <th>{{ day.1 }}</th>
                {% endfor %}
            </tr>
            {% for time in full_calendar %}
                <tr>
                    <td> {{ time|date:"G:i" }}</td>
                    {% for day in week_days %}
                        <td>
                            {% for training in object_list %}
                                {#                            {{ training.start_date_time.isoweekday|date:"d" }} {{ forloop.parentloop.counter|stringformat:"s" }}#}
                                {#                            training.start_date_time|date:"D" == day#}
                                {% if training.start_date_time|date:"D" == day.0 and training.start_date_time|date:"G:i" == time|date:"G:i" %}
                                    <a href="{% url 'swimming:trainings_detail' training.id %}">
                                        {{ training.group }}
                                    </a>
                                {% endif %}
                            {% endfor %}
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}